import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TanStackQueryProvider } from "@/tanstack-query/tanstack-query-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexal Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackQueryProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </TanStackQueryProvider>
        <Toaster
          closeButton
          toastOptions={{
            style: { boxShadow: "none", backgroundColor: "var(--background)" },
          }}
        />
      </body>
    </html>
  );
}
